apiVersion: docrepo/v1alpha1
kind: Manifest
metadata:
  name: jobs-configuration
resources:
  - name: dm_ConsistencyChecker
    resourceType: sysobject
    state: present
    selector:
      type: qualification
      dql: "dm_job where object_name = 'dm_ConsistencyChecker'"
      expectedType: dm_job
    spec:
      objectType: dm_job
      attributes:
        object_name: "dm_ConsistencyChecker"
        run_interval: 2
        is_inactive: true
  - name: dm_DataDictionaryPublisher
    resourceType: sysobject
    state: present
    selector:
      type: qualification
      dql: "dm_job where object_name = 'dm_DataDictionaryPublisher'"
      expectedType: dm_job
    spec:
      objectType: dm_job
      attributes:
        object_name: "dm_DataDictionaryPublisher"
        run_interval: 30
        is_inactive: false
  - name: dummy_test_job
    resourceType: sysobject
    state: present
    selector:
      type: qualification
      dql: "dm_job where object_name = 'dummy_test_job'"
      expectedType: dm_job
    spec:
      objectType: dm_job
      attributes:
        object_name: "dummy_test_job"
        run_interval: 2
        is_inactive: true
        method_name: "dummy_test_method"
